// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFollow = "follow"

// Follow mapped from table <follow>
type Follow struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`
	UID        int32     `gorm:"column:uid" json:"uid"`               // 被关注的uid
	FollowUID  int32     `gorm:"column:follow_uid" json:"follow_uid"` // 关注者的uid
	FollowTime time.Time `gorm:"column:follow_time;not null;default:CURRENT_TIMESTAMP" json:"follow_time"`
}

// TableName Follow's table name
func (*Follow) TableName() string {
	return TableNameFollow
}
