// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID     int32     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username   string    `gorm:"column:username;not null" json:"username"`
	Password   string    `gorm:"column:password;not null" json:"password"`
	UserIcon   string    `gorm:"column:user_icon;default:defaultIcon.png" json:"user_icon"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	DeleteTime string    `gorm:"column:delete_time" json:"delete_time"`
	UpdateTime time.Time `gorm:"column:update_time;not null" json:"update_time"`
	Email      string    `gorm:"column:email;not null" json:"email"`
	Sing       string    `gorm:"column:sing;default:这个人很懒，什么都没有留下" json:"sing"`
	Role       int32     `gorm:"column:role;default:1" json:"role"`
	UserBg     string    `gorm:"column:user_bg;default:defaultBg.png" json:"user_bg"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
