// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID     int32     `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"`
	Username   string    `gorm:"column:username;not null" json:"username"`                                 // 用户名
	Password   string    `gorm:"column:password;not null" json:"password"`                                 // 密码
	UserIcon   string    `gorm:"column:user_icon;default:defaultIcon.png" json:"user_icon"`                // 用户头像
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	DeleteTime string    `gorm:"column:delete_time" json:"delete_time"`                                    // 删除时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 最近更新时间
	Email      string    `gorm:"column:email;not null" json:"email"`                                       // 电子邮件
	Sing       string    `gorm:"column:sing;default:这个人很懒，什么都没有留下" json:"sing"`                            // 个性签名
	Role       int32     `gorm:"column:role;default:1" json:"role"`                                        // 角色权限
	UserBg     string    `gorm:"column:user_bg;default:defaultBg.png" json:"user_bg"`                      // 用户主页背景
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
