// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	Vid               int32     `gorm:"column:vid;primaryKey;autoIncrement:true" json:"vid"`           // 视频id
	VideoImage        string    `gorm:"column:video_image" json:"video_image"`                         // 视频封面地址
	Video             string    `gorm:"column:video" json:"video"`                                     // 视频地址
	VideoTitle        string    `gorm:"column:video_title" json:"video_title"`                         // 视频标题
	VideoIntroduction string    `gorm:"column:Video_introduction" json:"Video_introduction"`           // 视频简介
	UserID            int32     `gorm:"column:user_id" json:"user_id"`                                 // 视频作者id
	CreatTime         time.Time `gorm:"column:creat_time;default:CURRENT_TIMESTAMP" json:"creat_time"` // 视频创建时间
	Ischeck           bool      `gorm:"column:ischeck" json:"ischeck"`
	Isdelete          bool      `gorm:"column:isdelete" json:"isdelete"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
